spring:
  application:
    name: "migration-integrist-service"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
  datasource:
    url: "jdbc:postgresql://localhost:5432/old"
    username: old
    password: hehehe

springDoc:
  pathsToMatch: /**

---
spring:
  profiles: test
  h2:
    console:
      enables: true
  datasource:
    url: jdbc:h2:mem:old;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL